x='hello python!'
print(len(x))
print(x[len(x)-1])
print(x.count('o'))
print(x.count('py'))
print(x.count('py'))
print(x.find('py'))
print(x.find('py'))
print(x.index('py'))
print('-'.join(x))
print(x.upper())
print(x.lower())
print(x.replace('py','p'))
print(x.split(' '))